# Generated by Django 4.1.7 on 2023-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(max_length=2)),
                ('wing', models.CharField(choices=[('P', 'Paris'), ('B', 'Boulogne'), ('A', 'Auteuil')], max_length=1)),
                ('floor', models.IntegerField(max_length=1)),
                ('number', models.IntegerField(max_length=2)),
            ],
        ),
    ]
