# Generated by Django 4.2.1 on 2023-06-20 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RoomManager', '0005_alter_room_capacity_alter_room_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invited',
            field=models.ManyToManyField(default=None, related_name='event_invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_from_profile', to=settings.AUTH_USER_MODEL)),
                ('to_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_to_event', to='RoomManager.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_from_event', to='RoomManager.event')),
                ('to_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_to_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
