# Generated by Django 4.1.7 on 2023-06-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManager', '0009_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrequest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
