# Generated by Django 4.1.7 on 2023-06-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManager', '0011_eventinvite_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EventInvite',
        ),
    ]
